### ISSUE TITLE
Relative link goes to component instead to label.

### ISSUE THREAD

**Issue by clyfe** [Polymer/core-item#11] opened 2014-10-22 19:41 UTC
If I have a core item with a relative link inside it `<a href="#about" target="_self"></a>`, in a component, and I click the link, instead scrolling to the `#about` label in the current window I am sent to the containing component loaded as a html page.

This was ok in 0.4.2
Broken in master as of 9d71578cabfcc2a40a065d275262f4fd93f95369

See gist: https://gist.github.com/clyfe/ba7c8638b192a21d48cb

**Comment by ssorallen** [comment] 2015-01-14 19:43
This is due to URL rewriting done in Polymer itself. The issue is being tracked in https://github.com/Polymer/polymer/issues/651.

Closing this as a duplicate because `core-item` does not need to change.

**Closed by ssorallen** 2015-01-14 19:43 UTC
